"""add Id into Tables

Revision ID: a0b514dddc01
Revises: 3b7ed57085a5
Create Date: 2024-09-29 18:40:55.934723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b514dddc01'
down_revision: Union[str, None] = '3b7ed57085a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_index(op.f('ix_home_users_id'), 'home_users', ['id'], unique=False)
    op.add_column('role_users', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_index(op.f('ix_role_users_id'), 'role_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_users_id'), table_name='role_users')
    op.drop_column('role_users', 'id')
    op.drop_index(op.f('ix_home_users_id'), table_name='home_users')
    op.drop_column('home_users', 'id')
    # ### end Alembic commands ###
