"""create full model Database

Revision ID: f35a90e080a6
Revises: 5007ce47fdbb
Create Date: 2024-09-29 19:57:11.954654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35a90e080a6'
down_revision: Union[str, None] = '5007ce47fdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('return_device_id', sa.Integer(), nullable=True),
    sa.Column('execution_device_id', sa.Integer(), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], ),
    sa.ForeignKeyConstraint(['execution_device_id'], ['execution_device.id'], ),
    sa.ForeignKeyConstraint(['return_device_id'], ['return_device.id'], )
    )
    op.create_index(op.f('ix_command_devices_id'), 'command_devices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_devices_id'), table_name='command_devices')
    op.drop_table('command_devices')
    op.drop_table('command')
    # ### end Alembic commands ###
